name: Bug Report
description: Report a reproducible defect.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Provide enough detail for someone else to reproduce and validate a fix.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect?
      placeholder: Briefly describe the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: List exact steps, including commands if applicable.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Logs and Evidence
      description: Paste relevant logs, stack traces, screenshots, or failing output.
      render: shell
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Runtime/toolchain details.
      placeholder: Node 22.x, Python 3.11.x, OS, browser/client version.
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Who is affected and how severe is it?
    validations:
      required: true
